[package]
name = "ma-processor-host"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "ma-processor-host"
path = "src/main.rs"

[dependencies]
ma-processor = { path = "../ma-processor" }
serde = { workspace = true }
serde_json = { workspace = true }
