// Meeting Assistant detection-only extension (contract-extension-signal-delivery).
//
// The worker reports host and audible for the active tab to the local engine over the loopback
// channel. It reads nothing from a page, sends no URL path, query string or title, and captures no
// audio. Every message uses exactly the fields ExtensionMessage defines; the server rejects any
// other field.
//
// `./endpoint.js` is generated by the diagnostic harness (ma-diag) at engine start and is untracked
// build output: it carries the listener port, the per-start token and the meeting hostnames from
// the adapter tables. Without it the worker does nothing.

import { ENDPOINT } from "./endpoint.js";

// The wire fields, in the order contracts/extension-channel/message.schema.json declares them.
// The Rust test in ma-ext-channel compares this list with the schema.
export const MESSAGE_FIELDS = [
  "instance_id",
  "seq",
  "observed_at_ms",
  "host",
  "tab_key",
  "audible",
  "meeting_present",
];

const REPORT_PATH = "/report";
const TOKEN_HEADER = "X-MA-Token";

// One instance per worker start; the engine keeps a sequence space per instance.
const instanceId = crypto.randomUUID().replace(/-/g, "");
let seq = 0;
// Set once the engine answered 401: the token rotated (engine restart). The worker stops posting
// and records the condition; the operator reloads the extension after re-provisioning.
let tokenDead = false;
const lastReport = new Map(); // tabId -> "host|audible|meeting"

function hostnameOf(tab) {
  // The hostname is the only thing derived from the URL; the path and query never leave here.
  try {
    return new URL(tab.url).hostname;
  } catch {
    return null;
  }
}

function tabKeyOf(tab) {
  // Opaque per-tab key; never a title.
  return `tab-${tab.id}`;
}

export function buildMessage(tab, now) {
  const host = hostnameOf(tab);
  if (host === null) {
    return null;
  }
  seq += 1;
  const audible = tab.audible === true;
  const meetingPresent = ENDPOINT.meeting_hosts.includes(host);
  const values = {
    instance_id: instanceId,
    seq,
    observed_at_ms: now,
    host,
    tab_key: tabKeyOf(tab),
    audible,
    meeting_present: meetingPresent,
  };
  const message = {};
  for (const field of MESSAGE_FIELDS) {
    message[field] = values[field];
  }
  return message;
}

async function post(message) {
  if (tokenDead || !ENDPOINT || !ENDPOINT.port || !ENDPOINT.token) {
    return;
  }
  let response;
  try {
    response = await fetch(`http://127.0.0.1:${ENDPOINT.port}${REPORT_PATH}`, {
      method: "POST",
      headers: { "Content-Type": "application/json", [TOKEN_HEADER]: ENDPOINT.token },
      body: JSON.stringify(message),
    });
  } catch (e) {
    console.debug("ma-ext: listener unreachable", String(e));
    return;
  }
  if (response.status === 401) {
    tokenDead = true;
    console.warn("ma-ext: token rejected (engine restarted?); stopped posting until reload");
  } else if (response.status !== 204) {
    console.debug("ma-ext: report rejected", response.status);
  }
}

async function reportActiveTab() {
  const tabs = await chrome.tabs.query({ active: true, lastFocusedWindow: true });
  for (const tab of tabs) {
    const message = buildMessage(tab, Date.now());
    if (message === null) {
      continue;
    }
    const key = `${message.host}|${message.audible}|${message.meeting_present}`;
    if (lastReport.get(tab.id) === key) {
      continue;
    }
    lastReport.set(tab.id, key);
    await post(message);
  }
}

chrome.tabs.onUpdated.addListener((tabId, changeInfo) => {
  if ("audible" in changeInfo || "url" in changeInfo || "status" in changeInfo) {
    lastReport.delete(tabId);
    reportActiveTab();
  }
});
chrome.tabs.onActivated.addListener(() => reportActiveTab());
chrome.tabs.onRemoved.addListener((tabId) => lastReport.delete(tabId));
reportActiveTab();
